openapi: 3.0.0
info:
  title: "RossaVoice's Speech2Text API"
  version: '1.0'
  contact:
    name: Rossa Team
    email: hy@cinnamon.is
  description: "This document describes API for speech-to-text engine of RossaVoice.\n\n\n\nA flow of speech-to-text is described as follow.\n\n\n- First, uploading the audio file to our server via `POST /api/files`\n- Second, adding a speech-to-text job by `POST /api/jobs`\n- Third, checking the process by `GET /api/jobs/{job_id}/status`\n- Fourth, once you receive progess \"transcribed\" from `GET \n/api/jobs/{job_id}/status`, you can get the result by `GET /api/jobs/{job_id}`\n- Finally, discard the job by `DELETE /api/jobs/{job_id}`"
servers:
  - url: 'http://localhost:5000'
paths:
  '/api/jobs/{job_id}':
    parameters:
      - schema:
          type: string
        name: job_id
        in: path
        required: true
    delete:
      summary: 5. Removing Job
      responses:
        '204':
          description: |-
            No Content
            Successfully delete job.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  _state:
                    type: string
                    default: ERR
                  _error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                required:
                  - _state
                  - _error
              examples:
                example-400:
                  value:
                    _state: ERR
                    _error:
                      code: 404
                      message: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
      description: |-
        This API aims to remove:
        - finished job
        - running job
      operationId: delete-job-job_id
    get:
      summary: 4. Getting job
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - transcribing
                      - success
                  result:
                    type: array
                    description: Only available when status is `transcribed`
                    items:
                      type: object
                      properties:
                        start:
                          type: number
                          description: The start time of this transcript.
                        end:
                          type: number
                          description: The end time of this transcript.
                        speaker_number:
                          type: number
                          description: 'Speaker number talking from "start" to "end".'
                        transcript:
                          type: string
                          description: 'Transcript of "speaker_number" talking from "start" to "end".'
                      required:
                        - start
                        - end
                        - speaker_number
                        - transcript
                  number_conversion:
                    type: boolean
                  filler_tagging:
                    type: boolean
                  punctuation:
                    type: boolean
                  speaker_diarization:
                    type: boolean
                  _id:
                    type: string
                  _updated:
                    type: string
                  _created:
                    type: string
                  file_id:
                    type: string
                required:
                  - status
                  - result
                  - number_conversion
                  - filler_tagging
                  - punctuation
                  - speaker_diarization
                  - _id
                  - _updated
                  - _created
                  - file_id
              examples:
                example-200:
                  value:
                    _id: 5e735d3671870305ecf65ffd
                    file_id: 5e735d2e71870305ecf65ffc
                    speaker_diarization: false
                    number_conversion: true
                    punctuation: true
                    filler_tagging: false
                    _updated: 'Thu, 19 Mar 2020 11:53:26 GMT'
                    _created: 'Thu, 19 Mar 2020 11:53:26 GMT'
                    status: success
                    result:
                      - audio_path: assets/chiba0132-C.wav
                        start: 0.575
                        end: 4
                        transcript: でこないだ話なんですけど私の話ではなくもちろん
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  _state:
                    type: string
                    default: ERR
                  _error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                required:
                  - _state
                  - _error
              examples:
                example-400:
                  value:
                    _state: ERR
                    _error:
                      code: 404
                      message: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
      requestBody: {}
      operationId: get-job-job_id
      description: Get the result of a transcribed speech2text job.
    operationId: get-removejob
  '/api/jobs/{job_id}/status':
    get:
      summary: 3. Getting job status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  _updated:
                    type: string
                    format: date-time
                  _created:
                    type: string
                    format: date-time
                  status:
                    type: string
                required:
                  - _id
                  - _updated
                  - _created
                  - status
              examples:
                example-200:
                  value:
                    _id: 5e735d3671870305ecf65ffd
                    _updated: 'Thu, 19 Mar 2020 11:53:26 GMT'
                    _created: 'Thu, 19 Mar 2020 11:53:26 GMT'
                    status: success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  _error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                  _state:
                    type: string
                    default: ERR
                required:
                  - _state
                  - _error
              examples:
                example-400:
                  value:
                    _error:
                      code: 404
                      message: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
                    _state: ERR
      operationId: get-job-job_id-status
      description: This API aims to check the job status of added job (`POST /api/jobs`).
      requestBody: {}
    parameters:
      - schema:
          type: string
        name: job_id
        in: path
        required: true
  /api/jobs:
    parameters: []
    post:
      summary: 2. Adding Speech2Text Job
      operationId: post-job
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  _updated:
                    type: string
                    format: date-time
                  _created:
                    type: string
                    format: date-time
                  _id:
                    type: string
                  _state:
                    type: string
                    default: OK
                  file_id:
                    type: string
                  speaker_diarization:
                    type: boolean
                  punctuation:
                    type: boolean
                  filler_tagging:
                    type: boolean
                  number_conversion:
                    type: boolean
                  status:
                    type: string
                    default: transcribing
                    enum:
                      - transcribing
                      - success
                  file_name:
                    type: string
                required:
                  - _updated
                  - _created
                  - _id
                  - _state
                  - file_id
                  - speaker_diarization
                  - punctuation
                  - filler_tagging
                  - number_conversion
                  - status
              examples:
                example:
                  value:
                    _updated: 'Thu, 19 Mar 2020 11:53:26 GMT'
                    _created: 'Thu, 19 Mar 2020 11:53:26 GMT'
                    _id: 5e735d3671870305ecf65ffd
                    _state: OK
                    file_id: 5e735d2e71870305ecf65ffc
                    speaker_diarization: false
                    number_conversion: true
                    punctuation: true
                    filler_tagging: false
                    status: transcribing
                    file_name: 5e735d2e71870305ecf65ffa_chiba0132-C.wav
        '422':
          description: |
            Unprocessable Entity (WebDAV)

            In such case:
              - `file_id` is invalid because uploaded file with `file_id` is unavailable on server.
              - any field is in wrong type.
              - lack of required field(s).
          content:
            application/json:
              schema:
                type: object
                properties:
                  _error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                  _issues:
                    type: object
                    properties:
                      _exception:
                        type: string
                  _state:
                    type: string
                    default: ERR
                required:
                  - _state
                  - _error
              examples:
                example:
                  value:
                    _state: ERR
                    _issues:
                      speaker_diarization: required field
                    _error:
                      code: 422
                      message: 'Insertion failure: 1 document(s) contain(s) error(s)'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: string
                  description: '`_id` of uploaded file which was returned when using `POST /api/file`. '
                speaker_diarization:
                  type: boolean
                  description: 'Speaker diarization mode which indicates "who spoke what"'
                punctuation:
                  type: boolean
                  description: Punctuation adding
                filler_tagging:
                  type: boolean
                  description: Displaying filler mark
                number_conversion:
                  type: boolean
                  description: Converting kanji number into romanji number
              required:
                - file_id
                - speaker_diarization
                - punctuation
                - filler_tagging
                - number_conversion
        description: ''
      description: This API aims to add a speech to text job with the uploaded file (done in `POST /api/files`).
  /api/files:
    post:
      summary: 1. Uploading audio file
      operationId: post-file
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  _updated:
                    type: string
                    format: date-time
                  _created:
                    type: string
                    format: date-time
                  _id:
                    type: string
                    description: id of uploaded file on server
                  _state:
                    type: string
                    default: OK
                required:
                  - _updated
                  - _created
                  - _id
                  - _state
              examples:
                example-201:
                  value:
                    _updated: 'Thu, 19 Mar 2020 11:53:18 GMT'
                    _created: 'Thu, 19 Mar 2020 11:53:18 GMT'
                    _id: 5e735d2e71870305ecf65ffc
                    _state: OK
        '422':
          description: |-
            Unprocessable Entity
            Uploaded file is not in expected format/MIME type  .
          content:
            application/json:
              schema:
                type: object
                properties:
                  _state:
                    type: string
                    default: ERR
                  _issues:
                    type: object
                    properties:
                      _exception:
                        type: string
                  _error:
                    type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                required:
                  - _state
                  - _error
              examples:
                example-422:
                  value:
                    _state: ERR
                    _issues:
                      exception: Unsupported MIME type text/plain
                    _error:
                      code: 422
                      message: 'Insertion failure: 1 document(s) contain(s) error(s)'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: object
              required:
                - file
            examples: {}
        description: "This is form-data body. \nIt only has one key namely \"file\" and the value is the audio file attachment."
      description: |-
        This API aims to upload the file into the server.
        It supports for `POST /api/jobs` API that we can call with the file id.
      parameters: []
    parameters: []
components:
  schemas: {}
